[package]
name = "oktaws"
version = "0.1.0"
authors = ["Jonathan Morley <morley.jonathan@gmail.com>"]

[dependencies]
reqwest = "0.8.1"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
rusoto_core = "0.30.0"
rusoto_sts = "0.30.0"
rusoto_credential = "0.9.2"
scraper = "0.4.0"
base64 = "0.8.0"
quick-xml = "0.10.0"
rust-ini = "0.9"
structopt = "0.1.0"
structopt-derive = "0.1.0"
rpassword = "1.0.0"
text_io = "0.1.6"
failure = "0.1.1"
log = "0.3.8"
pretty_env_logger = "0.1.1"
keyring = "0.5.1"
username = "0.2.0"
