[package]
name = "oktaws"
version = "0.10.0"
authors = ["Jonathan Morley <morley.jonathan@gmail.com>"]
description = "Generates temporary AWS credentials with Okta."

[dependencies]
reqwest = "0.8.1"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
rusoto_core = "0.30.0"
rusoto_sts = "0.30.0"
rusoto_credential = "0.9.2"
base64 = "0.9.0"
rust-ini = "0.10.3"
structopt = "0.2.5"
structopt-derive = "0.2.5"
rpassword = "2.0"
text_io = "0.1.6"
failure = "0.1.1"
log = "0.4"
loggerv = "0.7.1"
keyring = "0.6"
username = "0.2.0"
toml = "0.4.5"
sxd-document = "0.2.6"
sxd-xpath = "0.4.1"
kuchiki = "0.7.0"

[patch.crates-io]
html5ever = { git = 'https://github.com/servo/html5ever', rev = '3d5e24bbc3ebadf4e1bb9a4e25dc24c80fed1670' }
