[package]
name = "oktaws"
version = "0.10.1"
authors = ["Jonathan Morley <morley.jonathan@gmail.com>"]
description = "Generates temporary AWS credentials with Okta."

[dependencies]
reqwest = "0.8.1"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
serde_str = "0.1.0"
toml = "0.4.5"
rusoto_core = "0.32.0"
rusoto_sts = "0.32.0"
rusoto_credential = "0.11.0"
base64 = "0.9.0"
structopt = "0.2.5"
structopt-derive = "0.2.5"
failure = "0.1.1"
log = "0.4"
loggerv = "0.7.1"
keyring = "0.6"
username = "0.2.0"
dialoguer = "0.1.0"
sxd-document = "0.2.6"
sxd-xpath = "0.4.1"
kuchiki = "0.7.0"
regex = "1.0.0"
serde_ini = "0.1.3"
path_abs = "0.4.0"
rpassword = "2.0.0"

[patch.crates-io]
# For https://github.com/servo/html5ever/pull/322
html5ever = { git = 'https://github.com/servo/html5ever', rev = '3d5e24bbc3ebadf4e1bb9a4e25dc24c80fed1670' }
# For https://github.com/rusoto/rusoto/pull/1001
rusoto_core = { git = 'https://github.com/rusoto/rusoto' }
# To support rusoto_core above
rusoto_credential = { git = 'https://github.com/rusoto/rusoto' }
