[package]
authors = ["Jonathan Morley <morley.jonathan@gmail.com>"]
description = "Generates temporary AWS credentials with Okta."
edition = "2018"
name = "oktaws"
version = "0.13.1"
[dependencies]
async-recursion = "*"
base64 = "0.13"
chrono = "*"
confy = "*"
dialoguer = "0.8"
dirs = "3"
failure = "0.1"
futures = "*"
glob = "0.3"
itertools = "0.10"
keyring = "0.10"
kuchiki = "0.8"
log = "0.4"
path_abs = "0.5"
paw = "*"
pretty_env_logger = "0.4"
regex = "1"
rusoto_core = "0.47"
rusoto_credential = "0.47"
rusoto_sts = "0.47"
rust-ini = "*"
samuel = "*"
serde_ini = "0.2"
username = "0.2"
walkdir = "2"

[dependencies.reqwest]
features = ["cookies", "json"]
version = "0.11"

[dependencies.serde]
features = ["derive"]
version = "1"

[dependencies.structopt]
features = ["paw"]
version = "0.3"

[dependencies.tokio]
features = ["full"]
version = "1"

[dependencies.url]
features = ["serde"]
version = "2.1"

[dev-dependencies]
tempfile = "3"

[target]
[target."cfg(linux)"]
[target."cfg(linux)".dependencies]
[target."cfg(linux)".dependencies.openssl]
features = ["vendored"]
version = "0.10"
