[package]
name = "oktaws"
version = "0.10.0"
authors = ["Jonathan Morley <morley.jonathan@gmail.com>"]
description = "Generates temporary AWS credentials with Okta."

[dependencies]
reqwest = "0.8.1"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
rusoto_core = "0.30.0"
rusoto_sts = "0.30.0"
rusoto_credential = "0.9.2"
scraper = { git = 'https://github.com/jonathanmorley/scraper', branch = 'stack_upgrade' }
base64 = "0.8.0"
quick-xml = "0.10.0"
rust-ini = "0.9"
structopt = "0.1.0"
structopt-derive = "0.1.0"
rpassword = "2.0.0"
text_io = "0.1.6"
failure = "0.1.1"
log = "0.4"
loggerv = "0.6"
keyring = "0.6"
username = "0.2.0"
toml = "0.4.5"
serde_ini = "0.1.3"

[patch.crates-io]
html5ever = { git = 'https://github.com/servo/html5ever' }
